### ISSUE TITLE
"Goto Declaration" doesn't handle .clang_complete

### ISSUE THREAD

**Issue by ivankravets** [yasuyuky/autocomplete-clang#105]
I've just updated to the latest version 0.9.1 and want to try "Go To" feature with [PlatformIO IDE](http://platformio.org/platformio-ide). However, it doesn't work for me. What is interesting, that code complete works fine. `Arduino.h` is located in `/Users/ikravets/.platformio/packages/framework-arduinoavr/cores/arduino`.
### Soure file

``` c++
/*
 * Blink
 * Turns on an LED on for one second,
 * then off for one second, repeatedly.
 */

#include "Arduino.h"

void setup()
{
  // initialize LED digital pin as an output.
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop()
{
  // turn the LED on (HIGH is the voltage level)
  digitalWrite(LED_BUILTIN, HIGH);
  // wait for a second
  delay(1000);
  // turn the LED off by making the voltage LOW
  digitalWrite(LED_BUILTIN, LOW);
   // wait for a second
  delay(1000);
}

```
### .clang_complete

```
-I/Users/ikravets/.platformio/packages/framework-arduinoavr/variants/standard
-I/Users/ikravets/.platformio/packages/framework-arduinoavr/cores/arduino
-I/Users/ikravets/.platformio/packages/toolchain-atmelavr/avr/include
-I/Users/ikravets/.platformio/packages/toolchain-atmelavr/bfd/include
-I/Users/ikravets/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.8.1/include
-I/Users/ikravets/.platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.8.1/include-fixed
-DF_CPU=16000000L
-DARDUINO_ARCH_AVR
-DARDUINO_AVR_UNO
-DARDUINO=10608
-DPLATFORMIO=020900
-D__AVR_ATmega328P__
```
### Error

```
<stdin>:7:10: fatal error: 'Arduino.h' file not found
#include "Arduino.h"
         ^

autocomplete-clang.coffee:84 1 error generated.
```

P.S: Thanks a lot for the awesome package!

**Comment by yasuyuky** [comment]
Thanks for your feedback.
How about v0.9.2?

**Comment by ivankravets** [comment]
```
autocomplete-clang.coffee:130 ReferenceError: ClangFlags is not defined(…)
autocomplete-clang.coffee:85 <stdin>:7:10: fatal error: 'Arduino.h' file not found

autocomplete-clang.coffee:85 #include "Arduino.h"
         ^

autocomplete-clang.coffee:85 1 error generated.
```

You don't need to make a quick release. I can test development version. Do you need additional information?

Thanks.

**Comment by yasuyuky** [comment]
> You don't need to make a quick release. I can test development version. 
Thanks, but I've released v.0.9.3. already 😅 
If v.0.9.3 does not solve this, I'll ask you first.

**Comment by ivankravets** [comment]
1. Thanks! Now it works... 😊 
2. I have problems related to Clang and specific arch's ASM. See http://pastebin.com/xv910uTH

These problems are not related to your package. I just want to ask for the better solution. In 99% it works well but dumps a few warnings what is OK. However, if some code contains GCC ASM Clang dies 😢 

Does Clang have special flags which allow ignoring these ASM errors? In this case, we can parse `.clang_complete` file for `-DPLATFORMIO=` and specify these hooks.

I understand that it is a very specific request. Nevertheless, embedded community will be thankful you for that.
