### ISSUE TITLE
Multiple "Go To Definition" items in the context menu

### ISSUE THREAD

**Issue by ivankravets** [yasuyuky/autocomplete-clang#106]
How about to have 1 item? 

![screen shot 2016-04-20 at 14 26 46](https://cloud.githubusercontent.com/assets/1760209/14673012/021a5d0c-0704-11e6-89e0-42de2bc44466.png)

**Comment by ivankravets** [comment]
Also, https://atom.io/packages/hyperclick is a good alternative.

**Comment by JayXon** [comment]
I think the "Go to Declaration" one (with a space between "Goto") comes from the symbols-view package
+1 for the hyperclick integration, autocomplete-python supports it.

**Comment by lierdakil** [comment]
symbols-view changed "Goto" to "Go to" a while back, so original intent was to override that I believe.
