### ISSUE TITLE
beautiful operators in autocomplete-plus demo

### ISSUE THREAD

**Issue by andre-dietrich** [yasuyuky/autocomplete-clang#107]
Hi yasusuky,

great tool, of course ;) but I was wondering, what did you use in your autocomplete-plus demo "video" so that the operators in your code were displayed in that nice format??? Could you enlighten me ;)

Regards

**Comment by yasuyuky** [comment]
Hi.
Maybe this is just what you are looking for :)
https://github.com/tonsky/FiraCode
