### ISSUE TITLE
autocomplete not finding vector header in c++

### ISSUE THREAD

**Issue by chaffra** [yasuyuky/autocomplete-clang#111]
I have a header file with 
# include <vector>

Getting this error in javascript console 

on.h:24:10: fatal error: 'vector' file not found
# include <vector>

**Comment by chaffra** [comment]
Ok this is because if I have a .h file, autocomplete assumes it's a c file instead of a c++ file. Is there a way to set my .h files to use c++ language, on a per project basis?

**Comment by treyzania** [comment]
I know this is ~1 year old now, but using the `.hpp` extension generally makes sure everything knows it's a C++ header.

**Comment by yasuyuky** [comment]
The package does not assume file type. 
Atom does.
There is the way to customize the behavior.

https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539

On per project basis, track this issue.

https://github.com/atom/atom/issues/5168
