### ISSUE TITLE
"Uncaught Error: write EPIPE" and "BufferedProcessError: Failed to spawn command `clang`. Make sure `clang` is installed and on your PATH"

### ISSUE THREAD

**Issue by ptck** [yasuyuky/autocomplete-clang#117]
Hi,
I have Atom on Ubunutu 14.04 and I installed linter-clang and autocomplete-clang.
However when I try to write in my C++-Program, these two errors appear:

"Uncaught Error: write EPIPE"
"BufferedProcessError: Failed to spawn command `clang`. Make sure `clang` is installed and on your PATH"

**Comment by HahaMango** [comment]
I also have this problem. 
So i turn to vscode to write code, now.
Are you fix this problem??

**Comment by TehWan** [comment]
You need to install clang before you can use this addon. On Windows, you may install it from the LLVM website, look for "Clang for Windows". Make sure to select the option to add it to your PATH during installation. Then restart Atom (reloading does not seem to be enough).

http://llvm.org/releases/download.html

Cheers,
JD

**Comment by HahaMango** [comment]
@TehWan  Thank.
