### ISSUE TITLE
quotation marks in compile_commands.json

### ISSUE THREAD

**Issue by cspanier** [yasuyuky/autocomplete-clang#128]
I do have a compile_commands.json with quotation marks within the command strings like this:
`"command": "/usr/local/bin/clang++ ... -DSOME_MACRO=\\\"some string with spaces\\\" ...",`

However, the code that splits this string into separate arguments fails and clang prints out a warning:
`missing terminating '"' character [-Winvalid-pp-token]at line 8 col 28 in <command line>`

Looking into clang-flags.coffee:41:
`config.command.replace(/\s+/g, " ").split(' ')`
seems to be the source of error. By replacing this line with
`allArgs = config.command.split(/"(\\"|[^"])*"|[^\s]+/g)`
the warning goes away.

**Comment by cmaaser** [comment]
erm.. sorry, that "fix" doesn't make much sense.. it just happend to work in my test environment. The following line should work:
`allArgs = config.command.replace(/("(\\"|[^"])*"|[^\s]+)\s*/g, "$1\0").split('\0')`
