### ISSUE TITLE
Cannot automatically write over hints after completion

### ISSUE THREAD

**Issue by futuretechmaker** [yasuyuky/autocomplete-clang#129]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/15630599/17275752/b81286f8-5712-11e6-83b7-8216aab0358d.gif)
After accepting a completion I have to manually select the hints for replacing them with actual code.

**Comment by yasuyuky** [comment]
Thanks for your feedback. 
This may be solved in latest version.
If not, feel free to reopen 😉
