### ISSUE TITLE
"The command line is too long" error on Windows

### ISSUE THREAD

**Issue by BrunoMPires** [yasuyuky/autocomplete-clang#134]
I'm using autocomplete-clang as part of the PlatformIO IDE on WIndows and noticed the plugin ceased working. When trying to invoke compeltion sugestions typing `ctrl-space`  I get the following error on the developer tools console:

```
The command line is too long. clang-provider.cofee:45
```

This issue was also reported in the PlatformIO community, [here](https://community.platformio.org/t/issue-autocomplete-messed-up-in-3-0/860/11). Any help, even temporary workarounds, would be much appreciated, thanks in advance.

**Comment by ivankravets** [comment]
We had the same problem in PlatformIO Build System. The solution is to save includes to a temporary file and call command with `@/path/to/file/with/includes`. See https://github.com/platformio/platformio/blob/develop/platformio/builder/tools/piowinhooks.py

**Comment by BrunoMPires** [comment]
Couldn't possibly the `.clang_complete` file be used as is? Using simply `@/path/to/.clang_complete` ?

**Comment by BrunoMPires** [comment]
@ivankravets  or @yasuyuky , could you provide some more info about the file format and comand line syntax that should be use in this case?

I've tried some variations here:
```
C:\Users\Pardal\Documents\UNESP-SerendipTec\Projetos\PhyNode>clang -fsyntax-only -xc++ -std=c++11 -Xclang -code-completi
on-macros -Xclang -code-completion-at=-:67:14 -I. @args.txt
```
But that leads to: `clang.exe: error: no input files`

**Comment by BrunoMPires** [comment]
@ivankravets @yasuyuky I've altered [clang-provider.cofee:37](https://github.com/yasuyuky/autocomplete-clang/blob/master/lib/clang-provider.coffee#L37) to pass `@args` file instead.

file is in the following nformat:
```
-fsyntax-only
-xc++
-std=c++11
-Xclang
-code-completion-macros
-Xclang
-code-completion-at=-:67:14
-I.
-IC:\\Users\\Pardal\\Documents\\UNESP-SerendipTec\\Projetos\\PhyNode\\src\\process
-Xclang -code-completion-brief-comments
-fparse-all-comments
-IC:\\Users\\Pardal\\.platformio\\packages\\framework-mbed\\hal\\api
-IC:\\Users\\Pardal\\.platformio\\packages\\framework-mbed\\hal\\hal
-IC:\\Users\\Pardal\\.platformio\\packages\\framework-mbed\\hal\\hal\\storage_abstraction
-IC:\\Users\\Pardal\\.platformio\\packages\\framework-mbed\\hal\\common
-IC:\\Users\\Pardal\\.platformio\\packages\\framework-mbed\\hal\\targets\\cmsis
```
Now I get something like this from Atom's console: 
```
Uncaught (in promise) TypeError: args.filter is not a function(…) buffered-process.coffee:56 
```

Any insights about this one?

**Comment by tly000** [comment]
I made a quick fix for this bug:

```coffeescript
  codeCompletionAt: (editor, row, column, language, prefix) ->
    command = atom.config.get "autocomplete-clang.clangCommand"
    args = @buildClangArgs(editor, row, column, language)
    fs = require 'fs'
    filename = path.dirname(editor.getPath()) + "/.autocomplete-clang-temp-args"
    fs.writeFile filename , args.join('\n'), (error) ->
      console.error("Error writing file", error) if error
    options =
      cwd: path.dirname(editor.getPath())
      input: editor.getText()

    new Promise (resolve) =>
      allOutput = []
      stdout = (output) => allOutput.push(output)
      stderr = (output) => console.log output
      exit = (code) => resolve(@handleCompletionResult(allOutput.join('\n'), code, prefix))
      args = ['@' + filename]
      bufferedProcess = new BufferedProcess({command, args, options, stdout, stderr, exit})
      bufferedProcess.process.stdin.setEncoding = 'utf-8';
      bufferedProcess.process.stdin.write(editor.getText())
      bufferedProcess.process.stdin.end()
```

you might see that this is only a dirty fix, it creates a file in your working directory, and the ```args = ['@' + filename]``` might fail, if the path contains spaces... using ```args = ['@"' + filename + '"']``` did not work, the file wasnt found that way, im not sure why :D

**Comment by ivankravets** [comment]
@tly000 how about to use temporary file for this task?

**Comment by tly000** [comment]
@ivankravets im not quite sure how to do it, this is the first time i wrote anything in coffee. do you mean creating a file inside the "%TEMP%" folder and then deleting it afterwards?

**Comment by ivankravets** [comment]
@tly000 you can use use this package https://www.npmjs.com/package/tmp

**Comment by AhMaizeBalls** [comment]
In case anyone needs it, I adjusted tly000's workaround to escape backslashes and spaces in the argument paths which wasn't the case for me before:

`  codeCompletionAt: (editor, row, column, language, prefix) ->
    command = atom.config.get "autocomplete-clang.clangCommand"
    args = @buildClangArgs(editor, row, column, language)
    args = args.join('\n')
    args = args.replace /\\/g, "\\\\"
    args = args.replace /\ /g, "\\\ "
    fs = require 'fs'
    filename = path.dirname(editor.getPath()) + "/.autocomplete-clang-temp-args"
    fs.writeFile filename , args, (error) ->
      console.error("Error writing file", error) if error
    options =
      cwd: path.dirname(editor.getPath())
      input: editor.getText()

    new Promise (resolve) =>
      allOutput = []
      stdout = (output) => allOutput.push(output)
      stderr = (output) => console.log output
      exit = (code) => resolve(@handleCompletionResult(allOutput.join('\n'), code, prefix))
      args = ['@' + filename]
      bufferedProcess = new BufferedProcess({command, args, options, stdout, stderr, exit})
      bufferedProcess.process.stdin.setEncoding = 'utf-8';
      bufferedProcess.process.stdin.write(editor.getText())
      bufferedProcess.process.stdin.end()`

**Comment by ivankravets** [comment]
@yasuyuky could you merge @AhMaizeBalls solution with own code refactoring?

A propose a few corrections:

1. Need to check `args` length. If it > 7000, then use a temporary file. Windows has a limit for 8192. Please note that path to clang and other options are included in this 8192, that is why I recommend to use 7000.
2. Use `path.join()` instead of hardcoded `/`.
3. Use `tmp` package instead of `.autocomplete-clang-temp-args` file in the project.

Thanks!

**Comment by yasuyuky** [comment]
Hi, thanks for your feedbacks.
I just released v0.11.0. 
This release includes a workaround for this.
Can I ask someone to check it?

**Comment by AhMaizeBalls** [comment]
Unfortunately, the error persists, however I think I managed to track it down:
On line 16 in clang-args-builder.coffee you have 
`      if args.length > (atom.config.get "autocomplete-clang.argsCountThreshold" or 7000)
`
and without much experience with coffee I'd guess that args.length refers to the number of elements in the array (evaluates to 128 on my setup)  and not the total number of characters of the containing elements (which is what seems to be the issue with the command line). On my install the console outputs args still as an array, so in order for this check to work you'd have to join args first.
But as I said, mostly speculation on my part :)
Thanks for looking into it!

**Comment by yasuyuky** [comment]
OK, I misunderstood Windows' argument restrictions.

```diff
-      if args.length > (atom.config.get "autocomplete-clang.argsCountThreshold" or 7000)
+      if (args.join " ").length > (atom.config.get "autocomplete-clang.argsCountThreshold" or 7000)
```

And this code is what we really need, right?

**Comment by AhMaizeBalls** [comment]
`if (args.join(" ")).length > (atom.config.get("autocomplete-clang.argsCountThreshold") or 7000)`

works, but the parentheses for the arguments are required.

**Comment by yasuyuky** [comment]
Thank you. I will release the patch release soon :+1:

**Comment by AhMaizeBalls** [comment]
Unfortunately 0.11.1 is still not working for me, I sent you a pull request of my working file...

**Comment by ivankravets** [comment]
@yasuyuky could you use `tmp` package instead of creating temporary files directly in the source folder? Atom's Tree View jumps every time when hidden files are visible. See screenshot below.

In summary, all works great: completion + goto declaration!

Thanks!

![screen shot 2017-04-21 at 16 22 46](https://cloud.githubusercontent.com/assets/1760209/25279404/01345016-26af-11e7-8cdf-47fe20e7597b.png)

**Comment by AhMaizeBalls** [comment]
@ivankravets This can easily be worked around by adding 
`.autocomplete-clang-*`
To the ignored files in the core settings

**Comment by ivankravets** [comment]
@AhMaizeBalls How do you think, should 200k developers do that especially for autocomplete-clang?

**Comment by AhMaizeBalls** [comment]
@ivankravets That's easy they  just add
.`autocomplete-clang-*`
To the ignored files in the core settings. (As a `workaround`)
That being said, that is still a far cry from some of the more "interesting" design choices in atom, so I'm sure people can live with it.

**Comment by ivankravets** [comment]
@AhMaizeBalls thanks, I know how to avoid this. I think about 300k developers who will update to the mew version. Do you have any ideas how to inform them to apply this hook/workaround? Or even, are you sure that we should do that?

We should fix a root of the problem and don't re-invent new wheel.

**Comment by ivankravets** [comment]
Also, see https://github.com/yasuyuky/autocomplete-clang/issues/134#issuecomment-294285576 and No.3

**Comment by yasuyuky** [comment]
Thank you for discussions.

@AhMaizeBalls 
Thanks for the workaround.
I think that it is reasonable to use os temp directory.

@ivankravets
It already uses `tmp` package.
So I think what we need is `os.tmpdir()`.

I push a [branch](https://github.com/yasuyuky/autocomplete-clang/tree/UseTmpdirForArgFile) for this change.
Could someone try this branch?

**Comment by AhMaizeBalls** [comment]
@yasuyuky your new branch now creates the `.autocomplete-clang-****` files in the user temp directory and the source directory of the project is untouched. Looks good!
I had to manually install the `tmp` package for the autocompletion to work but I assume that would happen automatically when autocomplete-clang is installed or updated via atom...

**Comment by ivankravets** [comment]
@yasuyuky Thanks for your time. No need to play with custom temporary file and os module. `tmp` package already does it automatically for us.

I've spent a few minutes and see https://github.com/yasuyuky/autocomplete-clang/pull/150

It works well. Would be thankful for the merge and release.

P.S: What do you think about https://github.com/yasuyuky/autocomplete-clang/issues/106? It's easy for implementing and `hyperclick` provides all information to handle "Go To declaration" with ctrl/cmd as we do that in generic IDE.

I can provide PR but you better know this package. See API for details: https://atom.io/packages/hyperclick

Thanks!
