### ISSUE TITLE
autocomplete-clang doesn't work

### ISSUE THREAD

**Issue by upeshjindal** [yasuyuky/autocomplete-clang#136]
Hi,

I'm using autocomplete-clang v0.10.0 with Atom on Mac OS X Sierra but so far I have not been able to see a single suggestion. The package appears to be quite attractive so I feel really helpless not being able to use it.

**Comment by bimmermeow** [comment]
Same here on Ubuntu 16.04 with installed `clang` package. Which packages have to be installed?
