### ISSUE TITLE
Uncaught Error: spawn clang ENOENT

### ISSUE THREAD

**Issue by stsdc** [yasuyuky/autocomplete-clang#14]
I got this error:
![zrzut ekranu z 2014-11-03 00 42 39](https://cloud.githubusercontent.com/assets/6031763/4877484/652dbdd6-62ea-11e4-8fb9-6266c373b449.png)

**Comment by alexandernst** [comment]
I got that too, in a Debian testing machine. The problem is that `clang` is actually `clang-3.x` in Debian, and I was using the default (`clang`) value in the package. It would be nice if this error could be shown in an error message box/popup instead of in the dev tools.
