### ISSUE TITLE
What's the "aren NaN:NaN"

### ISSUE THREAD

**Issue by NanerLee** [yasuyuky/autocomplete-clang#143]
When i select the **Goto Declaration**, it show me that:
![2017-01-17 16-47-40](https://cloud.githubusercontent.com/assets/16791509/22013662/2c79a6dc-dcd5-11e6-911d-efa20a418792.png)

What's the "aren NaN:NaN" ?

**Comment by clearmisp** [comment]
I wonder the same thing.
