### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by dac1976** [yasuyuky/autocomplete-clang#144]
Argument to `path.dirname` must be a string
```
Object.dirname (C:\Users\Duncan Crutchley\AppData\Local\atom\app-1.14.0\resources\app.asar\src\electron-shims.js:9:10)
ClangProvider.buildClangArgs (C:\Users\Duncan Crutchley\.atom\packages\autocomplete-clang\lib\clang-provider.coffee:160:25)
ClangProvider.codeCompletionAt (C:\Users\Duncan Crutchley\.atom\packages\autocomplete-clang\lib\clang-provider.coffee:48:19)
ClangProvider.getSuggestions (C:\Users\Duncan Crutchley\.atom\packages\autocomplete-clang\lib\clang-provider.coffee:41:21)
<unknown> (C:\Users\Duncan Crutchley\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:333:54)
Array.forEach (native)
```

**Comment by yangz15** [comment]
Object.dirname - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10
getFileContents - /Users/sahelanthropus/.atom/packages/autocomplete-clang/node_modules/clang-flags/lib/clang-flags.coffee:22:22
getClangFlagsCompDB - /Users/sahelanthropus/.atom/packages/autocomplete-clang/node_modules/clang-flags/lib/clang-flags.coffee:50:11
Object.getClangFlags - /Users/sahelanthropus/.atom/packages/autocomplete-clang/node_modules/clang-flags/lib/clang-flags.coffee:11:15
ClangProvider.buildClangArgs - /Users/sahelanthropus/.atom/packages/autocomplete-clang/lib/clang-provider.coffee:190:33
ClangProvider.codeCompletionAt - /Users/sahelanthropus/.atom/packages/autocomplete-clang/lib/clang-provider.coffee:48:19
Argument to path.dirname must be a string
Report Issue

**Comment by H2obrother** [comment]
Once I enable autocomplete-clang,this warning appears on the left down corner.

**Comment by mdable2** [comment]
I am having the same issue. Any guidance is much appreciated!

`autocomplete-clang (2 deprecations)

Argument to path.dirname must be a string
Object.dirname - C:\Users\markr\AppData\Local\atom\app-1.22.1\resources\app.asar\src\electron-shims.js:9:10
getCommonArgs - C:\Users\markr\.atom\packages\autocomplete-clang\lib\clang-args-builder.coffee:96:23
buildCodeCompletionArgs - C:\Users\markr\.atom\packages\autocomplete-clang\lib\clang-args-builder.coffee:56:13
ClangProvider.codeCompletionAt - C:\Users\markr\.atom\packages\autocomplete-clang-master\lib\clang-provider.coffee:40:14
ClangProvider.getSuggestions - C:\Users\markr\.atom\packages\autocomplete-clang-master\lib\clang-provider.coffee:34:21
providers.forEach.provider - <embedded>:42481:58

Argument to path.dirname must be a string

Object.dirname - C:\Users\markr\AppData\Local\atom\app-1.22.1\resources\app.asar\src\electron-shims.js:9:10
<unknown> - C:\Users\markr\.atom\packages\autocomplete-clang\lib\clang-args-builder.coffee:20:21
makeBufferedClangProcess - C:\Users\markr\.atom\packages\autocomplete-clang\lib\clang-args-builder.coffee:16:14
ClangProvider.codeCompletionAt - C:\Users\markr\.atom\packages\autocomplete-clang-master\lib\clang-provider.coffee:47:14
ClangProvider.getSuggestions - C:\Users\markr\.atom\packages\autocomplete-clang-master\lib\clang-provider.coffee:34:21
providers.forEach.provider - <embedded>:42481:58`
