### ISSUE TITLE
Autocomplete doesn't work with latest Clang v4.0.0 (Windows)

### ISSUE THREAD

**Issue by ivankravets** [yasuyuky/autocomplete-clang#153]
* http://releases.llvm.org/download.html

The latest release of LLVM v4.0.0 broke autocomplete support on Windows

@yasuyuky do you have any ideas?

**Comment by yasuyuky** [comment]
In my environment, clang v4.0.1 works,

```
/usr/local/opt/llvm/bin/clang --version 
clang version 4.0.1 (tags/RELEASE_401/final)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
```

If you use pre-compiled headers, remove them and try again.
Thank you.

**Comment by yasuyuky** [comment]
http://releases.llvm.org/4.0.0/tools/clang/docs/ReleaseNotes.html
... and according to the release notes, LLVM v4.0.0 does not drop the feature.
Feel free to reopen if you still have problem.
