### ISSUE TITLE
How to change version of C++

### ISSUE THREAD

**Issue by mstankus** [yasuyuky/autocomplete-clang#157]
The default for clang is version C+03.
I want to change it to a higher version and don't
see what to do.

**Comment by yasuyuky** [comment]
Use `Std c++` setting. 
Thank you.

<img width="500" alt="ghteam-auth 2017-08-04 11-32-41" src="https://user-images.githubusercontent.com/5463365/28951897-a50821bc-7908-11e7-91d5-058fc07d0cbd.png">
