### ISSUE TITLE
error on "Emit Precompiled Header"

### ISSUE THREAD

**Issue by bookar** [yasuyuky/autocomplete-clang#161]
with message: "Emiting precompiled header exit 1 See console for detailed error message"

**Comment by bookar** [comment]
and below is the console log:

> <embedded>:119181 IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:119181
clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~
1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~
1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

clang-provider.coffee:32 <stdin>:1:10: fatal error: 'ucos_ii.h' file not found
#include <ucos_ii.h>
         ^~~~~~~~~~~

1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

<embedded>:72862 Cannot find module '..\build\Release\pty.node'
(anonymous) @ <embedded>:72862
<embedded>:72865 Objectcode: "ENOENT"errno: -4058path: "C:\Users\sunliang9\.atom\packages\platformio-ide-terminal\node_modules\pty.js\bin\win32\x64_m53\pty.node.bak"syscall: "lstat"__proto__: Object
(anonymous) @ <embedded>:72865
autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.

autocomplete-clang.coffee:99 -emit-pch out
 
autocomplete-clang.coffee:100 -emit-pch err
 <stdin>:1:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~

1 error generated.

**Comment by DrakoPD** [comment]
Me too.

I need a solution.

atom 32 bits
Ubuntu 16.04 32 bits

**Comment by madhur4127** [comment]
clang couldn't find your files, be sure to include it in the include input box in settings of plugin.
