### ISSUE TITLE
No autocompletion with member initializer lists

### ISSUE THREAD

**Issue by en00x** [yasuyuky/autocomplete-clang#163]
As in the title mentioned, i have no autocompletion with member initializer lists.

E.g. this works:
![works](https://user-images.githubusercontent.com/13997715/32074433-b1089140-ba99-11e7-8f1c-6767fa4a0ab4.png)

But if i declare it in the header this example does not work:
![notworking](https://user-images.githubusercontent.com/13997715/32074495-e29c613c-ba99-11e7-8497-b6234700e22a.png)

The problem also occurs with libraries, so often methods are not shown in autocompletion.

Regards, en00x

**Comment by castleodinland** [comment]
I encountered the same problem.
It will show autocompletion after many times i input the same methods.
