### ISSUE TITLE
autocomplete does not seem to link to library path

### ISSUE THREAD

**Issue by trykks** [yasuyuky/autocomplete-clang#164]
Hi!

When trying to use the autocomplete-clang, there's nothing.

Run command is changed to installed version, clang-3.8 and include path is /opt/ros/lunar/*

typing for example "cv::" yields nothing.
All package dependencies are installed and active.

Any clues?

**Comment by DrakoPD** [comment]
I have the same problem, I use in Atom 32 bits on ubuntu 16.04 32 bits...

If you see the console, there are a list of errors. "ctrl+shift+i " linux

Any solution?
