### ISSUE TITLE
Multiple Issues/Improvements

### ISSUE THREAD

**Issue by archi** [yasuyuky/autocomplete-clang#17]
Hi, we have a rather complicated setup for a huge project, so had to modify autocomplete-clang a bit.
1: We have a lot of packages with the following dir structure:
package_name/Makefile
package_name/include/package/_.h
package_name/src/_.cpp
package_name/bin/_.{cpp,h}
package_name/tests/_
And a project/target consists of a set of these packages in a common folder.

Include paths (relative to package_name) are ./, ./include and ./../usr/include

atom runs clang in the subfolders, i.e. package_name/src/ for a cpp file. So I added a toggle to figure out where the Makefile is located and run clang there (or fall back to the subfolder if no Makefile can be located).

2: Clang produces errors for my project in the header file of std::vector (gcc version), but still outputs autocomplete information. Since I have no idea how to fix the "compile"/parsing error in <vector> and the project builds with g++ anyway, I added a toggle "Ignore Clang Errors".

3: Multiple Include Paths: I am new to atom.io, but the Include Path box is a text field and I could not figure out how to enter multiple include paths there. I took a look at the source, and neither the predefined value of ["."] nor the args.concat ("-I#{i}" for i in [...get that config option...]) didn't help me much.
I modified this to be the same as with linter-clang (single string with space separated paths), but that might be just a user issue ;-) [any help appreciated]

Anyway: If you want some of these changes I will fork and send you some pull requests. I think 1 + 2 are nice to have (while the third might be just due to my missing knowledge of atom/bad documentation on how to enter config stuff within the editor).

**Comment by jplatte** [comment]
Thanks a lot @yasuyuky, without the info that I have to seperate the values with commas I really would have been lost! Now at least this plugin works as expected. The same trick didn't help for linter-clang, but I'm sure I'll find a solution for that one too :)

**Comment by archi** [comment]
Sorry for not getting back, I am not on github that often (but will enable mail notification).
Is the issue 3rd suggestion still relevant? I am no native speaker [german here], but can try to improve the readme anyway ;-)
