### ISSUE TITLE
Is it possible to remove the namespace autocompletion?

### ISSUE THREAD

**Issue by xMC23x** [yasuyuky/autocomplete-clang#189]
I'm really liking this package so far, but if I type cout it transforms it into: "std::cout << "/* message */" << '\n';"

Is there a way to make this not happen if the namespace std is already defined? For now, my solution is to find all std:: and replace them with space. Sorry if it's a silly question, but I couldn't find anything in package settings.

**Comment by Xelbayria** [comment]
Did you figure it out? If yes, please share it here. I would like to know. Thanks

**Comment by uispnazionale** [comment]
> Did you figure it out? If yes, please share it here. I would like to know. Thanks

No, I didn't find a solution
