### ISSUE TITLE
Incompatible native modules

### ISSUE THREAD

**Issue by jrk** [yasuyuky/autocomplete-clang#24]
With the latest Atom (0.165.0) and autocomplete-clang (0.5.2), freshly installed from the package manager after deleting `~/.atom/packages/autocomplete-clang`, I find the module still failing to load with incompatible native modules:

    Failed to require the main module of 'autocomplete-clang' because it requires an incompatible native module
    Run `apm rebuild` in the package directory to resolve.

`apm rebuild` completes successfully, but does not resolve the issue.

This is on OS X 10.10.1 with Xcode 6.1.1. Help?

**Comment by jrk** [comment]
FWIW, this happens on a completely fresh `~/.atom` with no additional packages installed but autocomplete-clang.

**Comment by yasuyuky** [comment]
Hi. Thanks for your feedback.
This may be caused by incompatibility of the native code.
I just released the latest version v0.5.3 and it may solve this problem.
If you still have the problem, feedback again.
