### ISSUE TITLE
Can't get Clang Complete to do anything on Atom 0.169

### ISSUE THREAD

**Issue by IcyTesseract** [yasuyuky/autocomplete-clang#26]
I know that clang is properly installed, but toggeling Clang Complete doesn't show any sort of auto complete no matter what (other than the default Atom auto complete). There's no error messages provided in the dev console to help clarify what this issue is being caused by.

Also, I can confirm that the Vim Clang Complete plugin works fine so I'm nearly certain that this is not an issue with clang itself.

Edit: I've also tried using a `.clang_complete` file in the root directory, but this did not help.

**Comment by yasuyuky** [comment]
Thanks for your feedback.
The latest version v0.5.3 may solve this problem.
If you still have the problem, reopen the issue.
