### ISSUE TITLE
Language detection identifies C++ code as C

### ISSUE THREAD

**Issue by dschwen** [yasuyuky/autocomplete-clang#30]
The wrong language detection causes clang to be run with the wrong commands (i.e. stl includes are not found). Hardcoding `lang = "c++"` (instead of `lang = util.getFirstCursorSourceScopeLang @editor`) makes the package work on my c++ files.

This seems to be an issue with atom itself, as there does not seem to be a way to tell atom to autodetect `.h` and `.C` files as C++ rather than plain C.

So it would be nice to have an override in this package to transform lang "c" into "c++".

**Comment by Kev** [comment]
If you use .clang_complete, you can set this per-project along with other project-specific flags.

**Comment by dschwen** [comment]
Really? Is autocomplete-clang smart enough not to append a second language parameter to the clang options? After all .clang_autocomplete is just a list of options that are added to the clang command line.

**Comment by Kev** [comment]
There's no logic to prevent the dupe, but it works for me - presumably because clang is using the second -std= parameter and ignoring the first.
