### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by hammackj** [yasuyuky/autocomplete-clang#31]
Hello,

I can't seem to get the clang auto complete to work is there something that is required to enable it? I have it set for auto toggle and the guy lags when I do :: or -> but nothing pops up.

Any tips would be great. This plugin seems like it would be a life saver =)

Thanks.

**Comment by dschwen** [comment]
Open the development console in atom.io (alt+cmd i) and check if any errors are reported. Look in issue #21 for further steps.

**Comment by hammackj** [comment]
Thank you. My issue was I had to enable ignore clang errors, it wasn't able to find a include file.

I will close this, thanks.

**Comment by jplatte** [comment]
This seems to be the same issue I had. After selecting the "ignore clang error" option it works for me too. But cmd+alt+i doesn't do anything for me, so I can't find out which include file caused this problem.
