### ISSUE TITLE
Install/Compilation error 

### ISSUE THREAD

**Issue by gnzlbg** [yasuyuky/autocomplete-clang#35]
A couple of compilation errors while compiling `runas/src/main.o`:

```bash
In file included from ../src/main.cc:1:
../../nan/nan.h:623:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
```

```bash
../../nan/nan.h:1993:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
```

```bash
In file included from ../src/main.cc:1:
../../nan/nan.h:1995:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'
    ext = str->GetExternalAsciiStringResource();
          ~~~  ^
../../nan/nan.h:1996:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
```

**Comment by gnzlbg** [comment]
Seems to be caused by clang-flags:

https://github.com/Kev/clang-flags/issues/6

**Comment by KarateSnowMachine** [comment]
I think this is caused by autocomplete-clang using the older wanderer2/clang-flags instead of Kev/clang-flags. I think I have a working workaround on that issue tracker: https://github.com/Kev/clang-flags/issues/6

**Comment by yasuyuky** [comment]
Hi, All. Thanks for all your feedbacks. I'd really appreciate it.

**Comment by Kev** [comment]
Apologies - this happened because I got behind on merges and issues for the clang-flags package.

I'll try to sort out a release with all the fixes in, so that you're able to change back to pointing at a specific release, rather than needing to pull from trunk.
