### ISSUE TITLE
Autocomplete Clang 0.6.2, Incompatible package

### ISSUE THREAD

**Issue by WSoS** [yasuyuky/autocomplete-clang#40]
Hi,

With atom 0.186.0, I have this error with autocomplete clang :

Listed below are the incompatible native modules that this package depends on.

pathwatcher@3.3.1
Error message: Module version mismatch. Expected 41, got 17.
runas@2.0.0
Error message: Module version mismatch. Expected 41, got 17.

**Comment by Luthaf** [comment]
Running 
```
cd ~/.atom/package/autocomplete-clang/
rm -rf node_modules && apm install
```
resolved this issue for me.

**Comment by WSoS** [comment]
thank
