### ISSUE TITLE
Not compatible with Atom 0.187

### ISSUE THREAD

**Issue by andzaytsev** [yasuyuky/autocomplete-clang#42]
The latest version of Atom doesn't work with Autocomplete Clang 0.6.2. (Atom now ships with Chrome 40.0.2214.91 and Node 1.0.0-pre).

**Comment by yasuyuky** [comment]
Thanks for your feedback.
This might be a kind of 'Module version mismatch' problem like #46.
If not, feel free to reopen this issue.
