### ISSUE TITLE
Support for C++11

### ISSUE THREAD

**Issue by nafur** [yasuyuky/autocomplete-clang#44]
It would be very nice to support for different C++ standards.
As of now, we have -std=c++03 fixed in the plugin.

As a general fix (that also solves a few other problems I guess), I'd propose to (re-) introduce an option for command line arguments, where c++03 is set as a default (and not fixed in the code like now).

I've seen that the screenshot here on github shows a dedicated option for the c++ standard, however neither the code nor my installed version (0.6.2) seems to contain this option.

**Comment by yasuyuky** [comment]
Hi, thanks for the feedback.

The `std` option is still in code, but the current version of Atom GUI seems not to show structured options.

The quick solution is to add the code like below into your `config.cson` in `.atom` directory.

```cson
  "autocomplete-clang":
    std:
      "c++": "c++11"
```

I think this is inconvenient, and will try to get it back to the GUI preference.

Thank you.
