### ISSUE TITLE
Failed to load the autocomplete-clang package

### ISSUE THREAD

**Issue by andreiduca** [yasuyuky/autocomplete-clang#46]
Steps to reproduce:

1. update Atom to version 0.189.0
2. launch Atom

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang) package, v0.6.2

### Stack Trace

Failed to load the autocomplete-clang package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/andreiduca/.atom/packages/autocomplete-clang/node_modules/clang-flags/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/andreiduca/.atom/packages/autocomplete-clang/node_modules/clang-flags/node_modules/pathwatcher/lib/main.js:207:4)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-twig"
    ],
    "followSymlinks": true
  },
  "autocomplete-clang": {
    "preCompiledHeaders": {},
    "std": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-typescript, v1.19.0
autocomplete-clang, v0.6.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
emmet, v2.3.6
file-icons, v1.5.2
language-twig, v1.6.0
linter, v0.12.0
linter-clang, v2.25.1
linter-csslint, v0.0.11
linter-php, v0.0.12
linter-scss-lint, v0.0.14
minimap, v4.7.2
react, v0.10.1
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by eboracus** [comment]
Yes I get the exact same error, same Atom version and local system. Just to add that I tried with all other packages disabled and still get the same error, so I presume it's in the update to v0.189.

**Comment by yasuyuky** [comment]
Hi. Thanks for your feedbacks.
This is caused by dependency on 'pathwatcher' and going to be solved in the next version.
If you cannot wait,
doing `apm install` at your package directory of autocomplete-clang (it is `~/.atom/packages/autocomplete-clang/` if your environment is OS X) may fix this problem.

**Comment by eboracus** [comment]
Great, worked like a charm. Thanks for the info (and the package! :) )

**Comment by yasuyuky** [comment]
New version released and might solve this. 
If not, feel free to reopen the issue.

**Comment by axeoth** [comment]
Not a re-open necessarily, but it just happened to me with 0.190.0 on Linux 64, right after upgrade.

**Comment by axeoth** [comment]
ant the fix suggested by @yasuyuky corrected the problem

**Comment by komalsingh54** [comment]
I have this type of issue.
module version mismatch expected 43, got 46

I am using nwjs 0.12.3 app in windows 32 bit.
i installed visual studio 2013 express.
python 2.7.8
nodejs 

then i installed ffi
     npm install ffi
 then i build with nw-gyp
     nw-gyp configure --target=0.12.3
     nw-gyp rebuild --target=0.12.3
 when i run my app on nw.js it shows following error.
-> module version mismatch expected 43 get 46

i am stuck in this problem, please give me suggestion 
thanks
