### ISSUE TITLE
fail to emitting pch

### ISSUE THREAD

**Issue by raucha** [yasuyuky/autocomplete-clang#52]
I'm not native English speaker. Please allow me if my Eng is strange.
And i'm first at using coffescript, issue function of public repository.
Please point out me if i'm wrong.

In my environment, emitting pch function does not work and show aleart "autocomplete-clang:emit-pch\nError: Incompatible Language"
**Environment:**
Ubuntu 14.04
Atom 0.196.0

And finally I fixed this error ([here](https://github.com/yasuyuky/autocomplete-clang/compare/master...raucha:fix-emit-pch?expand=1)).
Can I make pull request by this repository?

**Comment by yasuyuky** [comment]
Thanks for your PR. It helps me very well!

**Comment by raucha** [comment]
いえーどういたしまして
初めてのプルリク緊張してたのでマージして貰えて嬉しいです。

**Comment by yasuyuky** [comment]
いえいえ、なかなかプルリクまでは貰えないので嬉しいです。
また気軽にお願いします。

**Comment by raucha** [comment]
はい、その時はまたよろしくお願いします
2015/05/03 18:15 "Yasuyuki YAMADA" <notifications@github.com>:
