### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by smlu** [yasuyuky/autocomplete-clang#56]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:11)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:234:14)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
```

**Comment by yasuyuky** [comment]
Thanks for your feedback.
I can not reproduce the problem.
Could you write down detailed versions of Atom and autocomplete-clang?
The code related to the config has been changed recently.
https://github.com/yasuyuky/autocomplete-clang/commit/504c33dc1aff5e0fc0b425726beeb398a31a8d61
Are you using the latest version of the package?

**Comment by smlu** [comment]
I've solved the problem now. I think the problem was with atom. Somehow it cached old version of plugin after i updated it even thou i restarted atom after update.
I think we can close the issue.
