### ISSUE TITLE
Jump to declaration

### ISSUE THREAD

**Issue by dschwen** [yasuyuky/autocomplete-clang#59]
Would it be possible to use the clang machinery to have a _jump to declaration_ function? If clang returns the locations where the current symbol is declared it should be trivial to open the file and jump to the correct position. I'll investigate this.

**Comment by adzenith** [comment]
Did you end up investigating this? I'd love to have this functionality as well!

**Comment by ivankravets** [comment]
+1

**Comment by dschwen** [comment]
I investigated quite a bit, but when I checked last there was no way to coerce the clang executable to spit out the locations of the declarations. I ended up using exuberant ctags to build a `.tags` file. It's not ideal as ctags does not really "understand" C++ but it is better than nothing.
A clang based solution would be better though.

**Comment by ivankravets** [comment]
@yasuyuky , do you have any ideas? 

Thanks a lot!

**Comment by dschwen** [comment]
https://github.com/Andersbakken/rtags may be the answer here

**Comment by dschwen** [comment]
Yeah, I just tested https://atom.io/packages/atomic-rtags together with rtags and it works amazingly well. I documented my steps here: http://mooseframework.org/wiki/atomio/

I think this is a solved problem.

**Comment by yasuyuky** [comment]
@ivankravets 
Using `libclang` with `node-ffi` may be a solution.
But I do not have time to do this work right now.

The way @dschwen pointed out is an alternative solution.
It seems to work well.
Thanks.

**Comment by dschwen** [comment]
rtags has the appeal of being fast (it (re-)indexes automatically in the background). The kicker is that it seems that rtags can even be utilized as an autocompletion backend! This would be waay faster than spawning clang repeatedly. rtags can also rename symbols globally. I will definitely keep an eye on it.

**Comment by yasuyuky** [comment]
Now it has a feature to jump to declaration.
