### ISSUE TITLE
Conflict with snippets

### ISSUE THREAD

**Issue by tewalds** [yasuyuky/autocomplete-clang#60]
If I start a snippet, say "if", it'll generate code like:
```
    if (/* condition */) {
        /* code */
    }
```
with ```/* condition */``` selected. If I type say "a." and let it give completions for a's methods, it will then select the ") {" and replace it for some reason. It'd be nice if the suggestions stayed within the parenthesis and still let me jump to the next snippet section with tab as usual.

**Comment by yasuyuky** [comment]
Thanks for your feedback.
This problem may be solved in v0.8.0 by using autocomplete-plus.
If not, feel free to reopen this issue.
Thanks.
