### ISSUE TITLE
Wrong working directory leading to clang errors

### ISSUE THREAD

**Issue by nafur** [yasuyuky/autocomplete-clang#61]
When I try to autocomplete in a file (say /home/user/project/test.h), the clang commandline looks like this:

```
clang++ -fsyntax-only -xc++ -Xclang -code-completion-at=-:97:19 -std=c++11 -I. -std=c++11 -working-directory=/home/user -
```

In my case, the file contains an include to another file in the same folder.
However, due to -working-directory=/home/user, clang is unable to locate this file.

**Comment by nafur** [comment]
I'd really like to use this plugin, but this error persists.
I tried to craft a patch fixing this bug, which turned out to basically remove the try block in buildClangArgs.

However, I hit another problem then: When completing in a header file, clang complains about having #pragma once in the main file and refuses to give any completions.
This can be fixed by using ```echo "#include \"filename.h\"" | clang++``` instead of ```cat filename.h | clang++```, i.e. simply changing the input option in codeCompletionAt().
This however requires that the file is actually saved before performing autocompletion...

**Comment by NeoRaider** [comment]
I've just looked into this, as I'm affected this bug as well. The issue lies in the "clang-flags" package, which always adds a `-working-directory=#{searchDir}` parameter to the clang call, where `searchDir` is the directory of the .clang_complete file. I think this should be fixed in clang-flags, but workarounding it in autocomplete-clang would also be easy.

**Comment by NeoRaider** [comment]
I've opened https://github.com/Kev/clang-flags/issues/11 . In the mean time, the following fixes the issue for me:

```diff
diff --git a/lib/clang-provider.coffee b/lib/clang-provider.coffee
index 2fe6064..09d6066 100644
--- a/lib/clang-provider.coffee
+++ b/lib/clang-provider.coffee
@@ -35,6 +35,7 @@ class ClangProvider
     options =
       cwd: path.dirname(editor.getPath())
       input: editor.getText()
+    args.push("-working-directory=#{options.cwd}")
 
     new Promise (resolve) =>
       allOutput = []
```
