### ISSUE TITLE
Disable selection of trailing characters

### ISSUE THREAD

**Issue by lczech** [yasuyuky/autocomplete-clang#64]
Every time the autocomplete list opens up, some of the characters after the cursor are selected. Sometimes just a few, sometimes everything until the end of the current line. After choosing a suggestion from the list, the selected text then is replaced by the autocompleted text. 

If the selected text was simply the symbol after the cursor, this might have been a feature. But as it is mostly a random amount of characters being selected, this is just annoying. Particularly when working with snippets:

* Type "if", hit tab to fill in the snippet. The following snippet appears, where the first comment is selected:

            if (/* condition */) {
                    /* code */
                }
            }
            
* Now type somthing that will trigger the autocomplete list. Suddenly, everything after the cursor is selected, in this case the brackets at the end: `) {`.
* Hit tab to fill in the suggestion. Now the brackets are gone. Annoying!

It would be nice to have either a proper selection of the next characters (in case it is a symbol that I want to replace by a new suggestions), or even better an option to fully disable this behaviour and simply not select any text at all.

**Comment by davidretler** [comment]
I have this issue as well. I made a gif demonstrating the issue: 

![test](https://cloud.githubusercontent.com/assets/1906526/8458895/ae29f9f4-1fe7-11e5-9a23-610e63da1f74.gif)

As can be seen, the regular autocomplete works fine, inserting the text at the cursor. However, this packages auto-complete selects some text and replaces it, causing the `if` statement to break.

A feature to disable selecting text would be highly appreciated.

**Comment by yasuyuky** [comment]
Thanks for your feedback.
This problem may be solved in v0.8.0 by using autocomplete-plus.
If not, feel free to reopen this issue.

**Comment by davidretler** [comment]
It seems to work now, awesome!
