### ISSUE TITLE
Plug into existing autocomplete infrastructure as a provider

### ISSUE THREAD

**Issue by ssfrr** [yasuyuky/autocomplete-clang#65]
It's great to have clang-backed autocompletions, and they seem to work better than autocomplete-ctags, which I also tried a bit.

I prefer the UI for the standard autocomplete package however. For instance, if you keep typing and ignore the autocomplete pop-up, I think that you should be able to type what you want without the plugin interfering (unless you press `tab` or `enter`). autocomplete-clang doesn't seem to work this way. I've also had some weird issues where hitting `tab` when the list is popped up puts it in some weird mode where the arrow keys actually move the box around. It may have something to do with vim-mode?

Anyways, it seems like it would be good to use the existing autocomplete functionality for the UI so that it's standard, and have this plugin just focus on interoperating with clang and acting as an autocomplete provider.

**Comment by ssfrr** [comment]
Just saw benogle/autocomplete-clang#1, so it looks like I'm not the first one to think of it. :smile:

**Comment by yasuyuky** [comment]
Thanks for your feedback :+1:
Now the mission completed ;)
