### ISSUE TITLE
Function argument completion should either handle closing `)` or add a tab target

### ISSUE THREAD

**Issue by ssfrr** [yasuyuky/autocomplete-clang#69]
If I define a function like:

```
void somefunc(int x, int y) {
    // does something with a point
}
```

Then later I want to use it like:

```
void bar(void) {
    somefunc(3, 9)
}
```

after I tab-complete `somefunct`, the plugin automatically shows me the function arguments and lets me tab between them, which is super cool.

The problem is that after I've typed the `9` I can't smoothly get out of the inside of the parentheses. Normally Atom automatically adds the matching closing paren and then allows you to type through it, i.e. when your cursor is before it and you type ')' you just move your cursor past the paren. Here it just adds another paren. Another option would be to allow the user to tab between the arguments and then press <tab> one more time to get past the closing paren.

**Comment by charlesswartz** [comment]
@ssfrr I submitted pull request #75 to address this issue.
