### ISSUE TITLE
Consider removing the word 'returns' from right label

### ISSUE THREAD

**Issue by maxbrunsfeld** [yasuyuky/autocomplete-clang#73]
Hi, thanks for making this package, and updating it to use autocomplete-plus!

Right now, the word `returns` (e.g. `returns int`, `returns void`) often takes up most of the space in the right-label of the autocomplete menu. If the type is long, it sometimes doesn't fit. Also, the word 'returns' is sometimes not correct, because the identifier being suggested is not a function. Personally, I think it would be better to remove the word 'returns' from the label.

**Comment by yasuyuky** [comment]
Thanks for your nice suggestion :+1:

**Comment by maxbrunsfeld** [comment]
Thanks!
