### ISSUE TITLE
Follow what linter-clang does and allow for "%p" in clang settings

### ISSUE THREAD

**Issue by mehcode** [yasuyuky/autocomplete-clang#74]

**Comment by Kerosene2000** [comment]
I am ok with this guy :+1: 

`.linter-clang-includes`
```
%p/corewar/include
%p/common
%p/common/libft/includes
```
can be interpreted by autocomplete-clang:
```
-I%p/corewar/include
-I%p/common
-I%p/common/libft/includes
```

or other solution:
use %p in the `.clang_complete` (rename to `.clang-complete` ?) ?
