### ISSUE TITLE
How do I add other library / headers?

### ISSUE THREAD

**Issue by benhj** [yasuyuky/autocomplete-clang#81]
Firstly many thanks for this great package. Anyway, I extensively develop with boost. Is it possible to get the same level of autocomplete with the boost libraries, using autocomplete clang?

Many thanks,
Ben.

**Comment by Phara0h** [comment]
I would also like to know this please :)

**Comment by MartinSandfuchs** [comment]
Simply add a file called `.clang_complete` into the root directory of your project (the one you open in atom). In this file you can include headers by setting include paths: `-I/path/to/include`

**Comment by koopdi** [comment]
This simply doesn't work for me. No headers can be found this way.
