### ISSUE TITLE
where can see error message for clang emit precompile header

### ISSUE THREAD

**Issue by seanchann** [yasuyuky/autocomplete-clang#82]
Hi:
    when I emit precompile header with C header. hava some error like:
   "Emiting precompiled header exit with 1 See console for detailed error mesage"

```
so , Where can I find this console,  see detailed error messaage. 
Thanks a lot !
```

**Comment by primitivorm** [comment]
Hi @seanchann:

Press Ctrl+Alt+I or View->Developer->Toggle Developer Tool
then open Console tab

See your error and comment us

**Comment by seanchann** [comment]
@primitivorm  thank you, I saw the error and fix it

**Comment by DrakoPD** [comment]
I have the same problem, but, I don't find a solution.

I use atom, 32 bits, on ubuntu 16.04 32 bits
