### ISSUE TITLE
Environment variables in .clang_complete

### ISSUE THREAD

**Issue by niedzielski** [yasuyuky/autocomplete-clang#88]
This is a feature request to add support for environment variables in .clang_complete files. For example, the following works well:

```
-I/home/stephen/opt/pebble/Pebble/chalk/include
```

But any of the following would be more portable:

```
-I$HOME/opt/pebble/Pebble/chalk/include
-I~/opt/pebble/Pebble/chalk/include
-I$PEBBLE/Pebble/chalk/include
```

**Comment by johnmccutchan** [comment]
+1

**Comment by shtirlic** [comment]
+1
Also some kind of wildcards like `-I/lib/**`  will be also great

**Comment by ivankravets** [comment]
+1

**Comment by Emilgardis** [comment]
+1

**Comment by tehe** [comment]
+1

**Comment by yasuyuky** [comment]
Hi. Thanks for your feedbacks! 
I think that your requests are reasonable. 
But this package use https://github.com/Kev/clang-flags to handle `.clang_complete`
So it is not the right place for the issue.
