### ISSUE TITLE
 fatal error: 'threads.h' file not found

### ISSUE THREAD

**Issue by donnib** [yasuyuky/autocomplete-clang#90]
When i try to emmit pch, how can i solve it ? I am on El Capitan

**Comment by ScriptorNY** [comment]
Same problem here

**Comment by kikko** [comment]
Anyone found a fix for that issue?
Same happening here with ubuntu 16.04.
I also have linter-clang installed

**Comment by kikko** [comment]
As it turns out it was the same issue as #30 and the fix described there fixed the issue for me.

**Comment by zzakafool** [comment]
it seems the <threads.h> is not supported by gcc. I can't find this file in my ArchLinux.
