### ISSUE TITLE
autocomplete-clang hides the suggestions of autocomplete-plus

### ISSUE THREAD

**Issue by Sheljohn** [yasuyuky/autocomplete-clang#93]
I'm getting this weird "bug" after I updated to Atom 1.5.3; when `autocomplete-clang` is enabled, it seems that the suggestions from `autocomplete-plus` (which include eg the names of the variables in all opened files, etc) are completely removed from the suggestion list, I can't see them at all. Can anyone else reproduce that bug?

**Comment by niosus** [comment]
I have exactly the same issue. No autocompletion from `autocomplete-plus` when `autocomplete-clang` is active. Atom 1.5.4.

**Comment by mr-frog** [comment]
This isn't quite a "bug", but it is how the package currently works. As you mention, the suggestions from `autocomplete-plus` are replaced by `autocomplete-clang`. I don't think it would be hard to append the suggestions from `autocomplete-clang` to `autocomplete-plus` instead.

Should this be the default behaviour / a package option?

**Comment by Sheljohn** [comment]
Well, the issue is that it also hides things you'd expect to get from auto-completion (like variables or function names). If there is any easy way to distinguish between such basic suggestions and ones that might conflict with `autocomplete-clang`, then imho it would be better to process the suggestions from `autocomplete-plus` before replacing them. Otherwise I think an option and a clear message in the package settings would make everything better :)
