### ISSUE TITLE
Using autocomplete-clang on Linux kernel code

### ISSUE THREAD

**Issue by useche** [yasuyuky/autocomplete-clang#95]
I'm trying to use autocomplete-clang with the linux kernel code. However, when running, I'm getting the following errors in the console:

clang: error: unknown argument: '-fno-delete-null-pointer-checks'
clang: error: unknown argument: '-maccumulate-outgoing-args'
clang: error: unknown argument: '-mfentry'
clang: error: unknown argument: '-fconserve-stack'
clang: error: unknown argument: '-fdebug-prefix-map=/usr/local/home/useche/a=.'

After this, there is no suggestion.

I'm using the compile_commands.json file.

**Comment by mr-frog** [comment]
All of these are command line options supported by GCC but not by Clang, which are used to compile the Linux kernel and have nothing to do with `autocomplete-clang`. Is there a .clang_complete file in the same directory as the source code that contains these flags?

**Comment by useche** [comment]
Nop. Only a compile_commands.json. Would it help if I remove this options from the compile_comands.json?

**Comment by mr-frog** [comment]
Yes, try this and hopefully it will work 😄. The commands in compile_commands.json are used by the Node.js package `clang-flags`, which in turn is used by `autocomplete-clang`. You might then have trouble trying to compile the code with GCC though.

**Comment by useche** [comment]
Removing the GCC flags made these errors go away, but I keep hitting other problems. I'm currently using YouCompleteMe (clang based) in vim with the same set of files and compile_commands.json file, and I don't hit so many errors. I wonder if there is something wrong in my atom configuration. I'll keep trying.
